[remote.github]
owner = "Stanley5249"
repo = "sioc-rs"

[changelog]
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{%- macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{%- endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
"""
trim = true
render_always = true
postprocessors = [
  { pattern = "<REPO>", replace = "https://github.com/Stanley5249/sioc-rs" },
]

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))" },
]
protect_breaking_commits = false
commit_parsers = [
  { message = ".*security", group = "<!-- 00 -->🛡️ Security" },
  { body = ".*security", group = "<!-- 00 -->🛡️ Security" },
  { message = "^feat", group = "<!-- 01 -->🚀 Features" },
  { message = "^fix", group = "<!-- 02 -->🐛 Bug Fixes" },
  { message = '^build\(deps\)', group = "<!-- 03 -->📦 Dependencies" },
  { message = "^perf", group = "<!-- 04 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 05 -->🚜 Refactor" },
  { message = "^doc", group = "<!-- 06 -->📚 Documentation" },
  { message = "^test", group = "<!-- 07 -->🧪 Testing" },
  { message = "^build", group = "<!-- 08 -->🏗️ Build" },
  { message = "^ci", group = "<!-- 09 -->👷 CI" },
  { message = "^style", group = "<!-- 10 -->🎨 Styling" },
  { message = "^chore: bump version", skip = true },
  { message = '^chore\(release\): prepare for', skip = true },
  { message = '^chore\(deps.*\)', skip = true },
  { message = '^chore\(pr\)', skip = true },
  { message = '^chore\(pull\)', skip = true },
  { message = "^chore", group = "<!-- 11 -->⚙️ Miscellaneous Tasks" },
  { message = "^revert", group = "<!-- 12 -->◀️ Revert" },
  { message = ".*", group = "<!-- 13 -->💼 Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
tag_pattern = "v[0-9].*"
link_parsers = []
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "newest"
recurse_submodules = false

[bump]
features_always_bump_minor = false
breaking_always_bump_major = false
