[package]
name = "eioc"
version.workspace = true
edition = "2024"
description = "Async Engine.IO client implementation for Sioc"
documentation = "https://docs.rs/eioc"
repository = "https://github.com/Stanley5249/sioc-rs"
license = "MIT OR Apache-2.0"
keywords = ["async", "engine-io", "networking", "websocket"]
categories = ["asynchronous", "network-programming", "web-programming"]

[dependencies]
base64.workspace = true
bytes.workspace = true
bytestring.workspace = true
futures-util.workspace = true
http.workspace = true
miette.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[features]
default = ["rustls-tls"]

native-tls = [
  "reqwest/native-tls",
  "tokio-tungstenite/native-tls",
]

rustls-tls = [
  "reqwest/rustls",
  "tokio-tungstenite/rustls-tls-native-roots",
]
