[package]
name = "sioc-socket"
version = "0.1.0"
edition = "2024"
description = "Async Socket.IO client implementation for Sioc"
repository = "https://github.com/Stanley5249/sioc-rs"
license = "MIT OR Apache-2.0"
keywords = ["async", "networking", "socketio", "websocket"]
categories = ["asynchronous", "network-programming", "web-programming"]

[dependencies]
bytes.workspace = true
bytestring.workspace = true
futures-util.workspace = true
miette.workspace = true
serde.workspace = true
serde_json.workspace = true
sioc-engine.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
