[package]
name = "sioc-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for Sioc"
repository = "https://github.com/Stanley5249/sioc-rs"
license = "MIT OR Apache-2.0"
keywords = ["codegen", "macros", "procedural-macro", "socketio"]
categories = [
  "development-tools::procedural-macro-helpers",
  "network-programming"
]

[lib]
proc-macro = true

[dependencies]
darling = "0.23"
heck = "0.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
sioc.workspace = true
