[package]
name = "sioc"
version.workspace = true
edition = "2024"
description = "Async Socket.IO client with type-safe event handling"
documentation = "https://docs.rs/sioc"
readme = "README.md"
repository = "https://github.com/Stanley5249/sioc-rs"
license = "MIT OR Apache-2.0"
keywords = ["async", "networking", "realtime", "socketio", "websocket"]
categories = ["asynchronous", "network-programming", "web-programming"]

[dependencies]
# Workspace dependencies
eioc.workspace = true
sioc-macros.workspace = true

bytes.workspace = true
bytestring.workspace = true
futures-util.workspace = true
miette.workspace = true
pin-project.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
axum = "0.8.9"
socketioxide = "0.18.3"
tokio = { workspace = true, features = ["full"] }
url.workspace = true
