[package]
name = "sioc-engine"
version = "0.1.0"
edition = "2024"
authors = ["Stanley5249 <seer852741@gmail.com>"]
description = "Async Engine.IO client implementation for Sioc"
license = "MIT OR Apache-2.0"

[features]
default = ["rustls-tls"]

native-tls = [
    "reqwest/native-tls",
    "tokio-tungstenite/native-tls",
]

rustls-tls = [
    "reqwest/rustls",
    "tokio-tungstenite/rustls-tls-native-roots",
]

[dependencies]
bytes.workspace = true
futures-util.workspace = true
miette.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
thiserror.workspace = true
tokio-tungstenite.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

base64 = "0.22"
http = "1"

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
